version: "3.1"


services:
  frontend:
    build: ./landing/
    ports:
      - 8080:8080

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    links:
      - mariadb_emails:mariadb_emails
    ports:
      - 8000:8000
    depends_on:
      - mariadb_emails

  mariadb_emails:
    image: mariadb/server:10.4
    #container_name: mariadb_emails
    environment:
      MARIADB_DATABASE: backend
      MARIADB_ROOT_PASSWORD: root
      #MARIADB_USER: back
      #MARIADB_PASSWORD: back
    #volumes:
    #  - ./db:/var/lib/mysql
    #ports:
    #  - 3306:3306

