FROM php:7.4.0

WORKDIR /app

COPY composer.json composer.json
COPY composer.lock composer.lock
COPY ./ ./

RUN apt update && apt install git -y

# Install Composer
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#RUN composer self-update --2

RUN docker-php-ext-install mysqli pdo pdo_mysql

#RUN composer install

#RUN php artisan migrate

EXPOSE 8000

CMD [ "php", "artisan", "serve", "--host", "0.0.0.0"]