FROM node:12.2.0-alpine

WORKDIR /app

COPY ./ ./

#RUN apt update -y

#RUN apt install nodejs npm -y

RUN npm install 

RUN npm rebuild node-sass

RUN npm install @vue/cli -g

EXPOSE 8080

CMD ["npm", "run", "serve"]